version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./nginx-webhook.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www/html
      - ./certs:/etc/nginx/certs
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - php
    networks:
      - webhook-network

  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    volumes:
      - ./www:/var/www/html
      - ./logs/php:/var/log/php
    networks:
      - webhook-network

networks:
  webhook-network:
    driver: bridge
