version: '3'

services:
  nginx:
    image: nginx:1.20
    container_name: efibank-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-webhook.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/efibank/certs
      - ./www:/var/www/efibank/www
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - php
    restart: always
    networks:
      - efibank-network

  php:
    image: php:7.4-fpm
    container_name: efibank-php
    volumes:
      - ./www:/var/www/efibank/www
      - ./logs:/var/log/efibank
    restart: always
    networks:
      - efibank-network

networks:
  efibank-network:
    driver: bridge
